### ISSUE TITLE
sed_eval.io.load_event_list does not support .csv

### ISSUE THREAD

**Issue by qiuqiangkong** [TUT-ARG/sed_eval#15]
Hi Toni, 

    I found the sed_eval.io.load_event_list function works well for .txt file. But when I change the suffix to .csv, it is parsing the events wrongly. Do you have any ideas? Many thanks! 

Qiuqiang

**Comment by toni-heittola** [comment]
`sed_eval.io.load_event_list` is basically a wrapper for `dcase_util.containers.MetaDataContainer().load()` and it should work equally well with CSV files. You might have to specify delimiter parameter as automatic delimiter detection might not always work properly. Furthermore, by default CSV file is assumed to have header row. You can disable this with  `csv_header` parameter, and give field names as list to `fields` parameter. See more [here](https://dcase-repo.github.io/dcase_util/generated/dcase_util.containers.MetaDataContainer.load.html#dcase_util.containers.MetaDataContainer.load)

An example how to use `load_event_list` for CSV file without a header row:

`sed_eval.io.load_event_list(csv_file, delimiter='\t', csv_header=False, fields=['filename','onset','offset','event_label'])`

If you still have a problem, can you provide an example of CSV file which is parsed wrongly to investigate this problem better.

**Comment by qiuqiangkong** [comment]
Hi Toni,


    Problem solved! As there is no header in the .csv file I am reading, I have to specify fields=['filename','onset','offset','event_label'] and it works!


    Thank you very much!


Best wishes,


Qiuqiang

________________________________
