### ISSUE TITLE
Process to generate Event list is CSV formatted text-file

### ISSUE THREAD

**Issue by n33lkanth** [TUT-ARG/sed_eval#18]
Hi @toni-heittola,
I am first time working on the SED task and got stuck in the generation of the Event list is CSV formatted text-file during the evaluation in Development dataset and Evaluation dataset of DCASE 2017 task 2 and 3. I can get the test predictions but am not sure about how to convert these frame-wise predictions to the time intervals (onset and offset time interval) for the Event list is CSV formatted text-file. Kindly help me to get any reference where I can learn this process from.

Stay Safe
Best Regards

**Comment by toni-heittola** [comment]
In order to convert frame-based predictions to onset-offset lists, one needs to go through frames in order and identify contiguous active regions. 

In the DCASE2017 baseline system, this is implemented here > https://github.com/TUT-ARG/DCASE2017-baseline-system/blob/master/dcase_framework/recognizers.py#L160

The same functionality has been later released in `dcase_util` package as method `dcase_util.data.DecisionEncoder.find_contiguous_regions`. Here is the tutorial how to use this > https://dcase-repo.github.io/dcase_util/tutorial_data.html#decision-encoding

This will give you a list of frame indices. In order to get onset and offset in seconds, one needs to multiply these with the analysis hop length (often feature extraction hop length).

**Comment by n33lkanth** [comment]
Hi @toni-heittola, thank you very much for sharing the detail. I will have a look at this. I have the following queries regarding DCASE 2017 Challenge:

1. In the case of the Mono SED task (DCASE 2017 Task 2) do we need to train three different models for each event with ground truth of length 1 i.e., either [0] or [1]? or there should be a single model with a dense layer of 3 units to detect the three events?
2. I came across one of the [examples](https://github.com/wuqiangch/icassp2019-tutorial/blob/master/code_examples/sound_event_detection_example.ipynb) created by you for DCASE 2017 task 3. However, I can see that you are downloading and preprocessing the dataset using the **_dcase_util library_**. But in my case, I need to use the already downloaded copy of the DCASE 2017 Task 3 dataset and need to extract Mel-spectrogram as the feature instead of Mel-band energy. So, is it possible to use the **_dcase_util library_** for analyzing and preprocessing the local copy of the dataset? 


Best Regards

**Comment by toni-heittola** [comment]
1. In DCASE2017 task 2, "Target sound event categories will be treated independently, therefore it is allowed to use completely different approaches for detection, tailored to the characteristics of each sound category." One solution for this is to build three separate systems (models).
2. dcase_util library has dataset classes to download, extract and handle metadata. If you specify `data_path` parameter to the directory with already downloaded zip packages, the download will be skipped. 
```
db = dcase_util.datasets.TUTSoundEvents_2017_DevelopmentSet(
    data_path=dataset_storage_path
).initialize()
```

**Comment by n33lkanth** [comment]
Hi @toni-heittola ,
Thank you for the confirmation. In my case the downloaded dataset is already extracted and merged in different directories as below:
dcase_2017_task_3\development\audio\street
dcase_2017_task_3\development\meta\evaluation_setup
dcase_2017_task_3\evaluation\audio\street
dcase_2017_task_3\evaluation\meta\evaluation_setup

**Comment by toni-heittola** [comment]
Then this should work:

```
db_dev = dcase_util.datasets.TUTSoundEvents_2017_DevelopmentSet(
    data_path='dcase_2017_task_3\development\'
).initialize()

db_eval = dcase_util.datasets.TUTSoundEvents_2017_EvaluationSet(
    data_path='dcase_2017_task_3\evaluation\'
).initialize()
```

Just place dev and eval dataset zip-packages under those folder. I will close this issue now as it is not about `sed_eval`.
