### ISSUE TITLE
Examples in docs for evaluating results directly in python without loading from files

### ISSUE THREAD

**Issue by justinsalamon** [TUT-ARG/sed_eval#4]
Currently the only example (I could find) in the documentation for using `sed_eval` in python assumes the reference and estimate events are saved to disk as lab files. It would be helpful to have an example showing how to use `sed_eval` to compare ref/est that live in memory directly, including the expected data format (`EventList`?). Thanks!

**Comment by toni-heittola** [comment]
This issue has been addressed in commit 52efb7a79699169986feae49c5b080abaf845966.
