### ISSUE TITLE
SegmentBasedMetrics constructor doesn't type check

### ISSUE THREAD

**Issue by justinsalamon** [TUT-ARG/sed_eval#5]
The `SegmentBasedMetrics` constructor take a list of valid event labels, which must be of type `list`. Giving it an `numpy.ndarray` will work during construction, but will cause the code to crash when calling `evaluate()` with a not-so-easy-to-parse error. It would be helpful if the constructor checked for the types of its two input args (list and float > 0) and raised errors if they are incorrect.

**Comment by toni-heittola** [comment]
This issue has been addressed in the commit 6c85bc6867c7bfdbe56fe338156b501013fe2222. 

Now numpy.ndarray is converted to list before usage to allow easier integration. Sound event evaluator (segment-based and event-based) parameters are now type checked and appropriate errors shown.
